"""initial schema

Revision ID: 77ada1122829
Revises: 
Create Date: 2026-06-01 01:29:56.841976

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77ada1122829'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aspect_ratio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_duration_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brief',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_project_id'), 'brief', ['project_id'], unique=False)
    op.create_table('characterprofile',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('face_lock', sa.JSON(), nullable=True),
    sa.Column('voice_lock', sa.JSON(), nullable=True),
    sa.Column('wardrobe_rules', sa.JSON(), nullable=True),
    sa.Column('forbidden_changes', sa.JSON(), nullable=True),
    sa.Column('reference_look_frame_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characterprofile_project_id'), 'characterprofile', ['project_id'], unique=False)
    op.create_table('scene',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('beats', sa.JSON(), nullable=True),
    sa.Column('est_duration_sec', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_project_id'), 'scene', ['project_id'], unique=False)
    op.create_table('stylepack',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lighting', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('camera_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('palette', sa.JSON(), nullable=True),
    sa.Column('negative_rules', sa.JSON(), nullable=True),
    sa.Column('look_frame_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stylepack_project_id'), 'stylepack', ['project_id'], unique=False)
    op.create_table('shot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('scene_order', sa.Integer(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('beat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('camera_spec', sa.JSON(), nullable=True),
    sa.Column('performance_spec', sa.JSON(), nullable=True),
    sa.Column('preferred_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acceptance_rules', sa.JSON(), nullable=True),
    sa.Column('reference_look_frame_ids', sa.JSON(), nullable=True),
    sa.Column('transition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shot_project_id'), 'shot', ['project_id'], unique=False)
    op.create_index(op.f('ix_shot_scene_id'), 'shot', ['scene_id'], unique=False)
    op.create_table('visualconceptset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scene_order', sa.Integer(), nullable=False),
    sa.Column('brief', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visualconceptset_project_id'), 'visualconceptset', ['project_id'], unique=False)
    op.create_index(op.f('ix_visualconceptset_scene_id'), 'visualconceptset', ['scene_id'], unique=False)
    op.create_table('lookframe',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concept_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('promoted_as', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['concept_set_id'], ['visualconceptset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookframe_concept_set_id'), 'lookframe', ['concept_set_id'], unique=False)
    op.create_index(op.f('ix_lookframe_project_id'), 'lookframe', ['project_id'], unique=False)
    op.create_table('shotversion',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_assets', sa.JSON(), nullable=True),
    sa.Column('output_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['shotversion.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shotversion_shot_id'), 'shotversion', ['shot_id'], unique=False)
    op.create_table('generationjob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shot_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['shot_version_id'], ['shotversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generationjob_shot_version_id'), 'generationjob', ['shot_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generationjob_shot_version_id'), table_name='generationjob')
    op.drop_table('generationjob')
    op.drop_index(op.f('ix_shotversion_shot_id'), table_name='shotversion')
    op.drop_table('shotversion')
    op.drop_index(op.f('ix_lookframe_project_id'), table_name='lookframe')
    op.drop_index(op.f('ix_lookframe_concept_set_id'), table_name='lookframe')
    op.drop_table('lookframe')
    op.drop_index(op.f('ix_visualconceptset_scene_id'), table_name='visualconceptset')
    op.drop_index(op.f('ix_visualconceptset_project_id'), table_name='visualconceptset')
    op.drop_table('visualconceptset')
    op.drop_index(op.f('ix_shot_scene_id'), table_name='shot')
    op.drop_index(op.f('ix_shot_project_id'), table_name='shot')
    op.drop_table('shot')
    op.drop_index(op.f('ix_stylepack_project_id'), table_name='stylepack')
    op.drop_table('stylepack')
    op.drop_index(op.f('ix_scene_project_id'), table_name='scene')
    op.drop_table('scene')
    op.drop_index(op.f('ix_characterprofile_project_id'), table_name='characterprofile')
    op.drop_table('characterprofile')
    op.drop_index(op.f('ix_brief_project_id'), table_name='brief')
    op.drop_table('brief')
    op.drop_table('project')
    # ### end Alembic commands ###
