"""add timeline_sequence

Revision ID: c3b7e6f929ab
Revises: 4bfd05b77083
Create Date: 2026-06-01 02:59:31.648007

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c3b7e6f929ab'
down_revision: str | None = '4bfd05b77083'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelinesequence',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shot_version_ids', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timelinesequence_project_id'), 'timelinesequence', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timelinesequence_project_id'), table_name='timelinesequence')
    op.drop_table('timelinesequence')
    # ### end Alembic commands ###
