"""add cost_usd

Revision ID: fdfb08911737
Revises: c3b7e6f929ab
Create Date: 2026-06-01 18:14:05.888750

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdfb08911737'
down_revision: str | None = 'c3b7e6f929ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generationjob', sa.Column('cost_usd', sa.Float(), nullable=False))
    op.add_column('imageasset', sa.Column('cost_usd', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imageasset', 'cost_usd')
    op.drop_column('generationjob', 'cost_usd')
    # ### end Alembic commands ###
